backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/images
public_folder: /images 

collections:
  - name: 'portfolio'
    label: 'Portfolio'
    folder: 'content/portfolio' 
    create: true
    slug: "{{slug}}"
    media_folder: '/images'
    public_folder: '/public'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'navbar'
    label: 'Navigation Bar'
    folder: 'content/navbar' 
    create: true
    slug: "{{slug}}"
    media_folder: '/images'
    public_folder: '/public'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slag', widget: 'string'}
      - { label: 'Page name', name: 'pageName', widget: 'list', allow_add: true, default: ["About", "Portfolio", "Gallery", "Contact", "Services"] }