backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/images
public_folder: /images 

collections:
  - name: 'teams'
    label: 'Team'
    folder: 'content/teams' 
    create: true
    slug: "{{slug}}"
    media_folder: '/images'
    public_folder: '/public'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: Company Position', name: 'cposition', widget: 'string' }
      - { label: 'Image', name: 'img', widget: 'image' }
  - name: 'portfolio'
    label: 'Portfolio'
    folder: 'content/portfolio' 
    create: true
    slug: "{{slug}}"
    media_folder: '/images'
    public_folder: '/public'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'Navbar'
    label: 'Navigation Bar'
    folder: 'content/Navbar' 
    create: true
    slug: "{{slug}}"
    media_folder: '/images'
    public_folder: '/public'
    editor:
      preview: true
    fields:
      - label: 'Pages'
        name: 'pages'
        widget: 'list' 
        allow_add: true
        fields: 
          - { label: 'Page name', name: pageName, widget: string}
          - { label: 'Url', name: src, widget: string}
        default: 
          - { pageName: "About", src: "/about"}
          - { pageName: "Portfolio", src: "/portfolio"}
          - { pageName: "Gallery", src: "/gallery"}
          - { pageName: "Services", src: "/services"}
          - { pageName: "FAQ", src: "/faq"}
    
